[versions]
detekt = "1.23.8"
guava = "33.5.0-jre"
kotlin = "2.3.0"
kotlinter = "5.4.0"
kotlinx-coroutines = "1.10.2"
mockk = "1.14.9"
mockwebserver = "5.3.2"
spring-boot = "4.0.2"

[libraries]
assertj = { module = "org.assertj:assertj-core" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jackson-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
junit = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"}
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
logback = { module = "ch.qos.logback:logback-classic" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver3", version.ref = "mockwebserver" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-webclient = { module = "org.springframework.boot:spring-boot-starter-webclient" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
